### ISSUE TITLE
'list' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by NeilWang079** [ZHO-ZHO-ZHO/ComfyUI-AuraSR-ZHO#1]
!!! Exception during processing!!! 'list' object has no attribute 'cpu'
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\comfyui\comfyui\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 247, in combine_video
    images = tensor_to_bytes(images)
  File "E:\comfyui\comfyui\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 89, in tensor_to_bytes
    return tensor_to_int(tensor, 8).astype(np.uint8)
  File "E:\comfyui\comfyui\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 84, in tensor_to_int
    tensor = tensor.cpu().numpy() * (2**bits-1)
AttributeError: 'list' object has no attribute 'cpu'

**Comment by keno-log** [comment]
how do you solve the issue?
